a="pythonprogramming"
print(a.lower())
print(a.upper())
print(a. title())
print(a.capitalize())
print(a.isdigit())
print(a.isalpha())
print(a.isalnum())
print(a.index('o'))
print(a.count('p'))
print(a.split())
print(a.strip())
